Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: github-integration

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: github-integration
      ContainerDefinitions:
        - Name: github-integration
          Image: github-integration:latest
          PortMappings:
            - ContainerPort: 8080

  Service:
    Type: AWS::ECS::Service
    DependsOn: TaskDefinition
    Properties:
      ServiceName: github-integration
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !Ref PrivateSubnet1
            - !Ref PrivateSubnet2
          SecurityGroups:
            - !Ref SecurityGroup
          AssignPublicIp: DISABLED

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: github-integration-vpc
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: us-east-1a

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: github-integration-vpc
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: us-east-1b

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: github-integration-vpc
      GroupDescription: Allow inbound traffic to my-container
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup

  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: github-integration-vpc
      GroupDescription: Allow inbound traffic to the load balancer
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  LoadBalancerDNSName:
    Description: The DNS name of the load balancer
    Value: !GetAtt Service.LoadBalancers[0].DNSName